# Generated by Django 4.0.1 on 2022-03-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asdsa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
